=== ivos/lightair-spring-sample/src/test/java/dataset.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:la="http://lightair.sourceforge.net/">
	<xsd:import namespace="http://lightair.sourceforge.net/" schemaLocation="light-air-types.xsd"/>

	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="customers" type="customers__Type"/>
				<xsd:element name="flyway_schema_history" type="flyway_schema_history__Type"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="customers__Type">
		<xsd:attribute name="id" use="optional" type="la:LongType"/>
		<xsd:attribute name="version" use="optional" type="la:LongType"/>
		<xsd:attribute name="name" use="optional" type="la:StringType"/>
		<xsd:attribute name="tax_number" use="optional" type="la:StringNullableType"/>
		<xsd:attribute name="maturity_interval" use="optional" type="la:IntegerType"/>
		<xsd:attribute name="mobile" use="optional" type="la:StringNullableType"/>
		<xsd:attribute name="email" use="optional" type="la:StringNullableType"/>
		<xsd:attribute name="web" use="optional" type="la:StringNullableType"/>
		<xsd:attribute name="updated" use="optional" type="la:TimestampType"/>
	</xsd:complexType>
	<xsd:complexType name="flyway_schema_history__Type">
		<xsd:attribute name="installed_rank" use="optional" type="la:IntegerType"/>
		<xsd:attribute name="version" use="optional" type="la:StringNullableType"/>
		<xsd:attribute name="description" use="optional" type="la:StringType"/>
		<xsd:attribute name="type" use="optional" type="la:StringType"/>
		<xsd:attribute name="script" use="optional" type="la:StringType"/>
		<xsd:attribute name="checksum" use="optional" type="la:IntegerNullableType"/>
		<xsd:attribute name="installed_by" use="optional" type="la:StringType"/>
		<xsd:attribute name="installed_on" use="optional" type="la:TimestampType"/>
		<xsd:attribute name="execution_time" use="optional" type="la:IntegerType"/>
		<xsd:attribute name="success" use="optional" type="la:BooleanType"/>
	</xsd:complexType>
</xsd:schema>

=== ivos/lightair-spring-sample/src/test/java/it/customer/list/ListCustomersIT.xml
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../dataset.xsd">

	<!--other-->
	<customers id="@auto" version="@auto" name="@auto" tax_number="@auto" maturity_interval="@auto" mobile="@auto"
	           email="@auto" web="@auto" updated="@auto"/>

	<!--name-->
	<customers id="@auto" version="@auto" name="Name ZCa" tax_number="@auto" maturity_interval="@auto" mobile="@auto"
	           email="@auto" web="@auto" updated="@auto"/>
	<customers id="@auto" version="@auto" name="Name ABc" tax_number="@auto" maturity_interval="@auto" mobile="@auto"
	           email="@auto" web="@auto" updated="@auto"/>
	<customers id="@auto" version="@auto" name="Name ABa" tax_number="@auto" maturity_interval="@auto" mobile="@auto"
	           email="@auto" web="@auto" updated="@auto"/>
	<customers id="@auto" version="@auto" name="Name AAa" tax_number="@auto" maturity_interval="@auto" mobile="@auto"
	           email="@auto" web="@auto" updated="@auto"/>

	<!--taxNo-->
	<customers id="@auto" version="@auto" name="@auto" tax_number="TaxNo ZCa" maturity_interval="@auto" mobile="@auto"
	           email="@auto" web="@auto" updated="@auto"/>
	<customers id="@auto" version="@auto" name="@auto" tax_number="TaxNo ABc" maturity_interval="@auto" mobile="@auto"
	           email="@auto" web="@auto" updated="@auto"/>
	<customers id="@auto" version="@auto" name="@auto" tax_number="TaxNo ABa" maturity_interval="@auto" mobile="@auto"
	           email="@auto" web="@auto" updated="@auto"/>
	<customers id="@auto" version="@auto" name="@auto" tax_number="TaxNo AAa" maturity_interval="@auto" mobile="@auto"
	           email="@auto" web="@auto" updated="@auto"/>

	<!--mobile-->
	<customers id="@auto" version="@auto" name="@auto" tax_number="@auto" maturity_interval="@auto" mobile="Mobile 601"
	           email="@auto" web="@auto" updated="@auto"/>
	<customers id="@auto" version="@auto" name="@auto" tax_number="@auto" maturity_interval="@auto" mobile="Mobile 503"
	           email="@auto" web="@auto" updated="@auto"/>
	<customers id="@auto" version="@auto" name="@auto" tax_number="@auto" maturity_interval="@auto" mobile="Mobile 502"
	           email="@auto" web="@auto" updated="@auto"/>
	<customers id="@auto" version="@auto" name="@auto" tax_number="@auto" maturity_interval="@auto" mobile="Mobile 501"
	           email="@auto" web="@auto" updated="@auto"/>

	<!--email-->
	<customers id="@auto" version="@auto" name="@auto" tax_number="@auto" maturity_interval="@auto" mobile="@auto"
	           email="Email ZCa" web="@auto" updated="@auto"/>
	<customers id="@auto" version="@auto" name="@auto" tax_number="@auto" maturity_interval="@auto" mobile="@auto"
	           email="Email ABc" web="@auto" updated="@auto"/>
	<customers id="@auto" version="@auto" name="@auto" tax_number="@auto" maturity_interval="@auto" mobile="@auto"
	           email="Email ABa" web="@auto" updated="@auto"/>
	<customers id="@auto" version="@auto" name="@auto" tax_number="@auto" maturity_interval="@auto" mobile="@auto"
	           email="Email AAa" web="@auto" updated="@auto"/>

	<!--web-->
	<customers id="@auto" version="@auto" name="web name 1" tax_number="@auto" maturity_interval="@auto" mobile="@auto"
	           email="@auto" web="Web ZCa" updated="@auto"/>
	<customers id="@auto" version="@auto" name="web name 2" tax_number="@auto" maturity_interval="@auto" mobile="@auto"
	           email="@auto" web="Web ABc" updated="@auto"/>
	<customers id="@auto" version="@auto" name="web name 3" tax_number="@auto" maturity_interval="@auto" mobile="@auto"
	           email="@auto" web="Web ABa" updated="@auto"/>
	<customers id="@auto" version="@auto" name="web name 4" tax_number="@auto" maturity_interval="@auto" mobile="@auto"
	           email="@auto" web="Web AAa" updated="@auto"/>

	<!--other-->
	<customers id="@auto" version="@auto" name="@auto" tax_number="@auto" maturity_interval="@auto" mobile="@auto"
	           email="@auto" web="@auto" updated="@auto"/>

</dataset>
